# Generated by Django 4.2.4 on 2023-08-17 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vms_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_number', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only Numbers & Characters')])),
                ('v_type', models.CharField(blank=True, choices=[], max_length=200, null=True)),
                ('v_model', models.TextField(blank=True, max_length=500, null=True)),
                ('v_description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
