# Generated by Django 4.2.4 on 2023-08-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms_records',
            name='v_type',
            field=models.CharField(blank=True, choices=[('TWO WHEELER', 'Two'), ('THREE WHEELER', 'Three'), ('FOUR WHEELER', 'Four')], max_length=200, null=True),
        ),
    ]
