# Generated by Django 4.2.4 on 2023-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0002_alter_vms_records_v_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms_records',
            name='v_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
