# Generated by Django 4.2.4 on 2023-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0003_alter_vms_records_v_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms_records',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vms_records',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
