# Generated by Django 4.2.4 on 2023-08-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0004_vms_records_created_vms_records_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vms_records',
            options={'ordering': ('-created',)},
        ),
    ]
