# Generated by Django 4.2.4 on 2023-08-19 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0007_alter_vms_records_v_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms_records',
            name='v_number',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}[\\s-]{0,1}[0-9]{2}[\\s-]{0,1}[A-Za-z]{1,2}[\\s-]{0,1}[0-9]{4}$', 'Only Numbers & Characters')], verbose_name='Vehicle Number'),
        ),
    ]
